"""
Calendar utilities for generating .ics files for interviews.
"""
from datetime import datetime, timedelta
from typing import Optional
import uuid


def generate_ics_file(
    title: str,
    description: str,
    start_datetime: datetime,
    duration_minutes: int = 60,
    location: str = "",
    organizer_email: str = ""
) -> str:
    """
    Generate an .ics calendar file content.

    Args:
        title: Event title (e.g., "Interview with Google - Software Engineer")
        description: Event description with details
        start_datetime: When the event starts
        duration_minutes: How long the event lasts (default: 60 minutes)
        location: Event location (physical address or video link)
        organizer_email: Organizer's email address

    Returns:
        String content of .ics file ready to download
    """
    # Calculate end time
    end_datetime = start_datetime + timedelta(minutes=duration_minutes)

    # Format datetimes for iCalendar format (YYYYMMDDTHHMMSSZ)
    start_str = start_datetime.strftime("%Y%m%dT%H%M%S")
    end_str = end_datetime.strftime("%Y%m%dT%H%M%S")
    created_str = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")

    # Generate unique ID
    uid = str(uuid.uuid4())

    # Escape special characters in text fields
    def escape_text(text: str) -> str:
        """Escape special characters for iCalendar format."""
        return text.replace("\\", "\\\\").replace(",", "\\,").replace(";", "\\;").replace("\n", "\\n")

    title = escape_text(title)
    description = escape_text(description)
    location = escape_text(location)

    # Build .ics content
    ics_content = f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Job Application Agent//Interview Calendar//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:{uid}
DTSTAMP:{created_str}
DTSTART:{start_str}
DTEND:{end_str}
SUMMARY:{title}
DESCRIPTION:{description}
LOCATION:{location}"""

    if organizer_email:
        ics_content += f"\nORGANIZER:mailto:{organizer_email}"

    # Add reminders (1 day before and 1 hour before)
    ics_content += """
BEGIN:VALARM
TRIGGER:-P1D
ACTION:DISPLAY
DESCRIPTION:Interview tomorrow
END:VALARM
BEGIN:VALARM
TRIGGER:-PT1H
ACTION:DISPLAY
DESCRIPTION:Interview in 1 hour
END:VALARM
END:VEVENT
END:VCALENDAR"""

    return ics_content


def create_interview_ics(
    company: str,
    role: str,
    interview_date: str,
    interview_time: str,
    duration_minutes: int = 60,
    location: str = "",
    notes: str = "",
    interviewer: str = ""
) -> str:
    """
    Create .ics file for an interview.

    Args:
        company: Company name
        role: Job role/title
        interview_date: Date in YYYY-MM-DD format
        interview_time: Time in HH:MM format (24-hour)
        duration_minutes: Interview duration (default: 60)
        location: Physical location or video call link
        notes: Additional notes about the interview
        interviewer: Interviewer name

    Returns:
        .ics file content string
    """
    # Parse date and time
    try:
        # Combine date and time
        datetime_str = f"{interview_date} {interview_time}"
        start_datetime = datetime.strptime(datetime_str, "%Y-%m-%d %H:%M")
    except ValueError as e:
        raise ValueError(f"Invalid date/time format: {e}")

    # Build title
    title = f"Interview: {company} - {role}"

    # Build description
    description = f"Interview with {company} for {role} position"
    if interviewer:
        description += f"\\nInterviewer: {interviewer}"
    if notes:
        description += f"\\n\\nNotes:\\n{notes}"
    description += "\\n\\nGenerated by Job Application Agent"

    return generate_ics_file(
        title=title,
        description=description,
        start_datetime=start_datetime,
        duration_minutes=duration_minutes,
        location=location
    )


def parse_interview_datetime(
    extracted_date: Optional[str],
    extracted_time: Optional[str]
) -> Optional[datetime]:
    """
    Parse interview date and time from extracted email data.

    Args:
        extracted_date: Date string in YYYY-MM-DD format (or None)
        extracted_time: Time string in HH:MM format (or None)

    Returns:
        datetime object or None if invalid/missing
    """
    if not extracted_date or not extracted_time:
        return None

    try:
        datetime_str = f"{extracted_date} {extracted_time}"
        return datetime.strptime(datetime_str, "%Y-%m-%d %H:%M")
    except (ValueError, AttributeError):
        return None


def format_interview_datetime_display(dt: datetime) -> str:
    """
    Format datetime for display in UI.

    Args:
        dt: datetime object

    Returns:
        Formatted string like "Mon, Feb 10, 2026 at 2:30 PM"
    """
    return dt.strftime("%a, %b %d, %Y at %I:%M %p")
